DROP DATABASE IF EXISTS DBVACINAVILMAR;

CREATE DATABASE DBVACINAVILMAR;

USE DBVACINAVILMAR;

CREATE TABLE PESSOA (
	IDPESSOA INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(200) NOT NULL
    , DATA_NASCIMENTO DATE NULL
    , SEXO CHAR(1) NOT NULL
    , CPF VARCHAR(11) NOT NULL UNIQUE
    , TIPO INT NOT NULL
    , CONSTRAINT PK_PESSOA PRIMARY KEY (IDPESSOA)
);

CREATE TABLE VACINA (
	IDVACINA INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(200) NOT NULL
    , PAIS_ORDIGEM VARCHAR(100) NOT NULL
    , ESTAGIO_PESQUISA VARCHAR(50) NOT NULL
    , DATA_INICIO_PESQUISA DATE NOT NULL
    , ID_PESQUISADOR_RESPONSAVEL INT NOT NULL
    , FASE ENUM('SOMENTE_PESQUISADOR','VOLUNTARIO','PUBLICO_GERAL') NOT NULL
    , QUANTIDADE_DOSES INT NOT NULL
    , CONSTRAINT PK_VACINA PRIMARY KEY (IDVACINA)
    , CONSTRAINT FK_VACINA_PESSOA FOREIGN KEY (ID_PESQUISADOR_RESPONSAVEL) REFERENCES PESSOA (IDPESSOA)
);

CREATE TABLE APLICACAO_VACINA (
	ID_APLICACAO_VACINA INT NOT NULL auto_increment
    , IDVACINA INT NOT NULL
    , IDPESSOA INT NOT NULL
    , DATA_APLICACAO DATE NOT NULL
    , NOTA INT NOT NULL
    , CONSTRAINT PK_APLICACAO_VACINA_PESSOA PRIMARY KEY (ID_APLICACAO_VACINA)
    , CONSTRAINT FK_APLICACAO_VACINA__VACINA FOREIGN KEY (IDVACINA) REFERENCES VACINA (IDVACINA)
    , CONSTRAINT FK_APLICACAO_PESSOA FOREIGN KEY (IDPESSOA) REFERENCES PESSOA (IDPESSOA)
);

-- PESSOA
INSERT INTO PESSOA (NOME, DATA_NASCIMENTO, SEXO, CPF, TIPO) VALUES ("FABIO", '1999-01-17', 'M', "1234567865", 1);
INSERT INTO PESSOA (NOME, DATA_NASCIMENTO, SEXO, CPF, TIPO) VALUES ("MARIA", '1980-05-20', 'F', "1234569511", 1);

-- VACINA
INSERT INTO VACINA (NOME, PAIS_ORDIGEM, ESTAGIO_PESQUISA, DATA_INICIO_PESQUISA, ID_PESQUISADOR_RESPONSAVEL, FASE, QUANTIDADE_DOSES)
	VALUES ("VAC 1", "BRA", "SOMENTE_PESQUISADOR", '2020-04-15', 1, 1, 2);
INSERT INTO VACINA (NOME, PAIS_ORDIGEM, ESTAGIO_PESQUISA, DATA_INICIO_PESQUISA, ID_PESQUISADOR_RESPONSAVEL, FASE, QUANTIDADE_DOSES)
	VALUES ("VAC 2", "ARG", "VOLUNTARIO", '2020-10-05', 2, 2, 2);

-- APLICACAO VACINA
INSERT INTO APLICACAO_VACINA (IDVACINA, IDPESSOA, DATA_APLICACAO, NOTA)
	VALUES (1, 2, '2020-10-20', 4);
INSERT INTO APLICACAO_VACINA (IDVACINA, IDPESSOA, DATA_APLICACAO, NOTA)
	VALUES (2, 1, '2020-06-10', 3);

select * from pessoa;

select * from vacina;

SELECT * FROM APLICACAO_VACINA;